---
title: "Project Check In 3"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
editor_options: 
  chunk_output_type: inline
---

------------------------------------------------------------------------

# Who

-   Amanda Lee, awl646
-   Nabil Yusufali, nay277

------------------------------------------------------------------------

# Data Set

-   <https://data.austintexas.gov/Environment/Water-Quality-Sampling-Data/5tye-7ray/about_data>

-   Austin Water Quality Sampling Data

-   Each row is a water quality sample by parameter, date, and location in Austin, TX. We are primarily interested in variables watershed, site_type, and result to understand the distribution of water quality across Austin.

-   There are 1,475,965 rows and 24 columns in the original data set. Because there is a lot of data, we have limited the data set to bacteria/pathogen samples. The data set 'water' contains 34893 rows and 24 columns.

```{r}
# Import 2024 Austin water quality sampling data set 
water <- read.csv('https://raw.githubusercontent.com/Amandawlee/sds322_project/refs/heads/main/Water_Quality_Sampling_Data.csv')

# Number of rows and columns in 'water'
dim(water)
```

------------------------------------------------------------------------

# Variables and Model

-   **Model 1 (Amanda)**: Predict if a bacteria/pathogen concentration sample is considered safe or unsafe.

    -   **Model Type**: Decision Tree
    
    -   **Outcome Variable and Type**: `safeness` (Categorical)

    -   **Predictors and Types**: `site_type` (Categorical), `parameter` (Categorical), `result` (Numerical)

-   **Model 2 (Nabil)**: Predict bacteria concentrations using time of day, type of water source, and site type.

    -   **Model Type**: Linear Regression
    
    -   **Outcome Variable and Type**: `Result`, Numeric

    -   **Predictors and Types**: `sample_date` (Numeric), `Medium` (Categorical), and `site_type` (Categorical).
